import type { AdapterDefinition } from "./types";

export const adapterDefinitions: AdapterDefinition[] = [
  {
    provider: "chatgpt",
    version: "1.2.2",
    hosts: ["chatgpt.com", "chat.openai.com"],
    sessionPatterns: [/\/c\/([^/?#]+)/, /\/g\/[^/]+\/c\/([^/?#]+)/],
    conversationRootSelector: "main",
    messageSelectors: ["[data-message-author-role]", "[data-message-id]"],
    userHints: ['[data-message-author-role="user"]'],
    assistantHints: ['[data-message-author-role="assistant"]'],
    reasoningSelectors: ['[data-message-content-part-type="reasoning"]'],
    toolSelectors: ['[data-message-author-role="tool"]'],
    streamingSelectors: ['button[data-testid="stop-button"]'],
  },
  {
    provider: "gemini",
    version: "1.2.0",
    hosts: ["gemini.google.com"],
    sessionPatterns: [/\/app\/([^/?#]+)/],
    conversationRootSelector: ".conversation-container, main",
    messageSelectors: ["user-query, model-response", "[data-test-id='conversation-turn']", ".conversation-container user-query, .conversation-container model-response"],
    userHints: ["user-query", "[data-test-id='user-query']", ".user-query"],
    assistantHints: ["model-response", "[data-test-id='model-response']", ".model-response"],
    reasoningSelectors: [".thoughts-container", "[data-test-id*='thought']"],
    toolSelectors: [".tool-call", "[data-test-id*='tool']"],
    streamingSelectors: ["button[aria-label*='Stop']", "button[aria-label*='停止']"],
  },
  {
    provider: "grok",
    version: "1.2.0",
    hosts: ["grok.com"],
    sessionPatterns: [/\/c\/([^/?#]+)/, /\/chat\/([^/?#]+)/],
    conversationRootSelector: "main",
    messageSelectors: [
      "[data-testid='user-message'], [data-testid='assistant-message']",
      ".message-bubble[data-testid]",
      "[data-message-id]",
      "[data-role]",
      "main article",
    ],
    userHints: [
      "[data-testid='user-message']",
      "[data-role='user']",
      ".message-user",
    ],
    assistantHints: [
      "[data-testid='assistant-message']",
      "[data-role='assistant']",
      ".message-assistant",
    ],
    reasoningSelectors: [
      ".thinking-container",
      "[data-testid*='thinking']",
      "[data-testid*='reasoning']",
      "[class*='reasoning']",
    ],
    toolSelectors: [
      "[data-testid*='tool']",
      "[data-testid='canvas-working-indicator']",
      "[class*='tool-call']",
      "[class*='tool-usage']",
    ],
    streamingSelectors: ["button[aria-label*='Stop']", "button[aria-label*='停止']"],
  },
  {
    provider: "yuanbao",
    version: "1.2.2",
    hosts: ["yuanbao.tencent.com"],
    sessionPatterns: [/\/chat\/([^/?#]+\/[^/?#]+)/],
    conversationRootSelector: "[class*='agent-chat__list'], main",
    messageSelectors: ["[data-message-id]", "[class*='message-item']", "[class*='agent-chat__list__item']"],
    userHints: ["[data-role='user']", "[class*='user-message']"],
    assistantHints: ["[data-role='assistant']", "[class*='assistant-message']", "[class*='answer']"],
    reasoningSelectors: ["[class*='reasoning']", "[class*='thinking']"],
    toolSelectors: ["[class*='tool']", "[class*='search-process']"],
    streamingSelectors: ["button[aria-label*='停止']", "[class*='stop-generate']"],
  },
  {
    provider: "minimax_agent",
    version: "1.3.0",
    hosts: ["agent.minimax.io", "agent.minimaxi.com"],
    sessionPatterns: [/\/chat\/([^/?#]+)/, /\/agent\/([^/?#]+)/],
    conversationRootSelector: "main, [class*='chat']",
    sessionQueryKeys: ["id", "chatId", "conversationId", "sessionId"],
    messageSelectors: [
      "[data-testid='message-item']",
      "[data-message-id]",
      "[data-role]",
      "[class*='message-item']",
    ],
    userHints: [
      "[data-testid='user-message-bubble']",
      "[data-role='user']",
      "[class*='user-message']",
    ],
    assistantHints: [
      "[data-testid='assistant-active-flow']",
      "[data-testid='activity-group']",
      "[data-role='assistant']",
      "[class*='assistant-message']",
    ],
    reasoningSelectors: [
      "[data-testid*='thinking']",
      "[class*='reasoning']",
      "[class*='thinking']",
      "details",
    ],
    toolSelectors: [
      "[data-testid='activity-group']",
      "[class*='tool']",
      "[class*='task-step']",
      "[class*='search-step']",
    ],
    streamingSelectors: [
      "[data-testid='stop-button']",
      "button[aria-label*='Stop']",
      "button[aria-label*='停止']",
    ],
  },
  {
    provider: "deepseek",
    version: "1.2.0",
    hosts: ["chat.deepseek.com"],
    sessionPatterns: [/\/a\/chat\/s\/([^/?#]+)/, /\/chat\/([^/?#]+)/],
    conversationRootSelector: "main, [class*='chat']",
    sessionQueryKeys: ["sessionId", "chatId"],
    messageSelectors: ["[data-message-id]", "[data-role]", "[class*='message']"],
    userHints: ["[data-role='user']", "[class*='user-message']", "[class*='question']"],
    assistantHints: ["[data-role='assistant']", "[class*='assistant-message']", "[class*='answer']"],
    reasoningSelectors: ["[class*='reasoning']", "[class*='thinking']", "[class*='deep-think']"],
    toolSelectors: ["[class*='search-result']", "[class*='tool']"],
    streamingSelectors: ["button[aria-label*='停止']", "[class*='stop-button']"],
  },
  {
    provider: "qianwen",
    version: "1.3.0",
    hosts: ["qianwen.com", "www.qianwen.com"],
    sessionPatterns: [/\/chat\/([^/?#]+)/, /\/conversation\/([^/?#]+)/],
    conversationRootSelector: "main, [class*='chat']",
    sessionQueryKeys: ["conversationId", "sessionId", "chatId"],
    messageSelectors: [
      "[data-role], [data-message-id], [class*='chat-message'], [class*='chatMessage'], [class*='message-item'], [class*='messageItem'], [class*='question'], [class*='answer']",
      "[class*='chat-message'], [class*='chatMessage']",
      "[class*='message-item'], [class*='messageItem']",
      "[class*='question'], [class*='answer']",
      "[data-message-id]",
      "[data-role]",
    ],
    userHints: ["[data-role='user']", "[class*='user-message']", "[class*='userMessage']", "[class*='question']"],
    assistantHints: ["[data-role='assistant']", "[class*='assistant-message']", "[class*='assistantMessage']", "[class*='answer']", "[class*='response']", "[class*='reply']"],
    reasoningSelectors: ["[class*='reasoning']", "[class*='thinking']", "details"],
    toolSelectors: ["[class*='search-step']", "[class*='tool']", "[class*='process']"],
    streamingSelectors: ["button[aria-label*='停止']", "[class*='stop-generate']"],
  },
  {
    provider: "kimi",
    version: "1.2.0",
    hosts: ["www.kimi.com", "kimi.com"],
    sessionPatterns: [/\/chat\/([^/?#]+)/, /\/kimiplus\/[^/]+\/([^/?#]+)/],
    conversationRootSelector: "main, [class*='chat']",
    sessionQueryKeys: ["conversationId", "chatId", "sessionId"],
    messageSelectors: ["[data-message-id]", "[data-role]", "[class*='chat-content-item']", "[class*='message-item']"],
    userHints: ["[data-role='user']", "[class*='user-content']", "[class*='question']"],
    assistantHints: ["[data-role='assistant']", "[class*='assistant-content']", "[class*='answer']"],
    reasoningSelectors: ["[class*='reasoning']", "[class*='thinking']", "details"],
    toolSelectors: ["[class*='search-process']", "[class*='tool']", "[class*='agent-step']"],
    streamingSelectors: ["button[aria-label*='停止']", "[class*='stop-button']"],
  },
];
